import { useEffect, useState } from 'react';
import { BarChart3, TrendingUp, DollarSign, Users, RefreshCw, Target } from 'lucide-react';
import { analyticsApi } from '../../services/api';
const money=(n:number)=>`KSh ${Number(n||0).toLocaleString(undefined,{maximumFractionDigits:0})}`;
export default function Analytics(){
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[days,setDays]=useState('30');
 const load=async()=>{setLoading(true);try{const end=new Date(), start=new Date();start.setDate(end.getDate()-Number(days)+1);const r=await analyticsApi.getAdvanced({startDate:start.toISOString().slice(0,10),endDate:end.toISOString().slice(0,10)});setData(r.data?.data)}finally{setLoading(false)}};
 useEffect(()=>{load()},[days]); const a=data?.analytics, s=data?.summary;
 const orderPulse=a?.salesTrend||[]; const maxOrders=Math.max(...orderPulse.map((x:any)=>Number(x.orders||0)),1); const totalOrders=orderPulse.reduce((n:number,x:any)=>n+Number(x.orders||0),0); const peakDay=orderPulse.reduce((best:any,x:any)=>Number(x.orders||0)>Number(best?.orders||0)?x:best,null);
 return <div className="rms-page max-w-7xl mx-auto"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><div className="rounded-xl bg-orange-100 p-2 text-orange-600"><BarChart3 size={21}/></div><h1 className="text-2xl font-bold">Advanced analytics</h1></div><p className="mt-1 text-sm text-gray-500">Sales intelligence, profitability and customer performance.</p></div><div className="flex gap-2"><select value={days} onChange={e=>setDays(e.target.value)}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option></select><button onClick={load} className="rms-btn rms-btn-secondary"><RefreshCw size={16} className={loading?'animate-spin':''}/> Refresh</button></div></div>
 {loading&&!data?<div className="rms-surface p-10 text-center text-gray-500">Loading analytics…</div>:<>
 <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[[DollarSign,'Gross margin',`${(a?.grossMarginPercentage||0).toFixed(1)}%`,money(s?.grossProfitEstimate)], [Target,'Food cost',`${(a?.foodCostPercentage||0).toFixed(1)}%`,money(s?.totalCost)], [Users,'Repeat purchase',`${(a?.repeatPurchaseRate||0).toFixed(1)}%`,`${a?.repeatCustomers||0} repeat customers`], [TrendingUp,'Next-day estimate',money(a?.forecastNextDaySales),`Based on recent sales`]].map(([Ico,title,value,sub]:any)=>{const Icon=Ico;return <div className="rms-surface p-5" key={title}><div className="flex justify-between"><div><p className="text-xs text-gray-500">{title}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-gray-400">{sub}</p></div><Icon className="text-orange-500" size={22}/></div></div>})}</div>
 <div className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_1fr]"><div className="rms-surface p-5"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">Order volume</h2><p className="text-xs text-gray-500">Completed orders by day — a clearer operational measure than sales-value bars.</p></div><div className="rounded-xl bg-orange-50 p-2 text-orange-600 dark:bg-orange-500/10"><BarChart3 size={20}/></div></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3"><div className="rounded-xl bg-[#faf9f7] p-3 dark:bg-[#111116]"><p className="text-[10px] uppercase tracking-wider text-gray-400">Orders</p><p className="mt-1 text-xl font-bold">{totalOrders}</p></div><div className="rounded-xl bg-[#faf9f7] p-3 dark:bg-[#111116]"><p className="text-[10px] uppercase tracking-wider text-gray-400">Daily average</p><p className="mt-1 text-xl font-bold">{orderPulse.length ? (totalOrders/orderPulse.length).toFixed(1) : '0.0'}</p></div><div className="rounded-xl bg-[#faf9f7] p-3 dark:bg-[#111116]"><p className="text-[10px] uppercase tracking-wider text-gray-400">Peak day</p><p className="mt-1 text-xl font-bold">{peakDay?.orders || 0}</p></div></div><div className="mt-5 flex h-48 items-end gap-1.5">{orderPulse.length ? orderPulse.map((x:any)=><div className="group flex min-w-0 flex-1 flex-col items-center" title={`${x.date}: ${x.orders || 0} completed orders`} key={x.date}><div className="w-full rounded-t-md bg-orange-500/85 transition hover:bg-orange-600" style={{height:`${Math.max(x.orders?8:2,(Number(x.orders||0)/maxOrders)*100)}%`}}/><span className="mt-2 text-[9px] text-gray-400">{x.date.slice(5)}</span></div>) : <div className="flex w-full items-center justify-center rounded-xl border border-dashed border-orange-100 bg-orange-50/40 dark:border-gray-800 dark:bg-[#111116]/40"><p className="text-sm text-gray-500">No completed orders in this period.</p></div>}</div><p className="mt-3 text-xs text-gray-400">Peak day: {peakDay?.date || '—'} with {peakDay?.orders || 0} completed orders.</p></div>
 <div className="rms-surface p-5"><h2 className="font-semibold">Business pulse</h2><p className="text-xs text-gray-500">Key outcomes for this period</p><div className="mt-6 space-y-5">{[['Completed orders',s?.orderCount||0],['Average order value',money(s?.averageOrderValue)],['Gross sales',money(s?.grossSales)],['Discounts given',money(s?.totalDiscounts)]].map(([k,v])=><div key={String(k)}><div className="flex justify-between text-sm"><span className="text-gray-500">{k}</span><b>{v}</b></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-orange-50 dark:bg-[#111116]"><div className="h-full rounded-full bg-orange-500" style={{width:'68%'}}/></div></div>)}</div></div></div>
 <div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rms-surface overflow-hidden"><div className="p-5"><h2 className="font-semibold">Product profitability</h2><p className="text-xs text-gray-500">Top products by sales and estimated margin</p></div><div className="overflow-auto"><table className="w-full text-sm"><thead className="bg-orange-50/60 text-left text-xs text-gray-500 dark:bg-[#111116]"><tr><th className="p-3">Product</th><th>Sales</th><th>Profit</th><th>Margin</th></tr></thead><tbody>{(a?.topProducts||[]).map((p:any)=><tr key={p.id} className="border-t border-orange-50 dark:border-gray-800"><td className="p-3 font-medium">{p.name}</td><td>{money(p.sales)}</td><td>{money(p.profit)}</td><td><span className="rounded-full bg-orange-50 px-2 py-1 text-xs text-orange-700 dark:bg-orange-500/10 dark:text-orange-300">{p.margin.toFixed(0)}%</span></td></tr>)}</tbody></table></div></div>
 <div className="rms-surface overflow-hidden"><div className="p-5"><h2 className="font-semibold">Branch performance</h2><p className="text-xs text-gray-500">Completed sales by branch</p></div><div className="space-y-3 p-5 pt-0">{(a?.branchPerformance||[]).length?(a.branchPerformance.map((b:any)=><div key={b.id} className="rounded-xl border border-orange-100 p-3 dark:border-gray-800"><div className="flex justify-between"><b>{b.name}</b><span className="text-orange-600">{money(b.sales)}</span></div><p className="mt-1 text-xs text-gray-500">{b.orders} completed orders</p></div>)):<p className="text-sm text-gray-500">No branch sales in this period.</p>}</div></div></div>
 </>}</div>
}
