import { Router } from 'express';
import { authenticate } from '../middleware/auth';
import { authorize } from '../middleware/auth';
import { getShifts, getCurrentShift, openShift, closeShift } from '../services/shiftService';
import { safeRouter } from '../utils/safeRouter';
const router=safeRouter(); router.use(authenticate);
router.get('/', authorize('OWNER','ADMIN','MANAGER','CASHIER'), getShifts);
router.get('/current', authorize('OWNER','ADMIN','MANAGER','CASHIER'), getCurrentShift);
router.post('/', authorize('OWNER','ADMIN','MANAGER','CASHIER'), openShift);
router.post('/:id/close', authorize('OWNER','ADMIN','MANAGER','CASHIER'), closeShift);
export default router;
