import { useEffect, useState } from 'react';
import { Bell, CheckCheck, Settings2, Mail, MessageSquare, Smartphone, RefreshCw } from 'lucide-react';
import { notificationApi } from '../../services/api';

export default function Notifications() {
 const [items,setItems]=useState<any[]>([]); const [prefs,setPrefs]=useState<any>(null); const [loading,setLoading]=useState(true); const [showPrefs,setShowPrefs]=useState(false);
 const load=async()=>{setLoading(true); try { const [n,p]=await Promise.all([notificationApi.getAll(),notificationApi.getPreferences()]); setItems(n.data?.data?.notifications||[]); setPrefs(p.data?.data?.preference); } finally {setLoading(false)}};
 useEffect(()=>{load()},[]);
 const markAll=async()=>{await notificationApi.markAllRead(); load()};
 const save=async()=>{await notificationApi.updatePreferences(prefs); setShowPrefs(false)};
 return <div className="p-6 max-w-6xl mx-auto">
  <div className="flex flex-wrap justify-between gap-4 mb-6"><div><div className="flex items-center gap-2"><Bell className="text-orange-500"/><h1 className="text-2xl font-bold">Notifications</h1></div><p className="text-sm text-gray-500 mt-1">Stay informed about orders, inventory, purchases and customer activity.</p></div><div className="flex gap-2"><button onClick={load} disabled={loading} className="px-4 py-2 rounded-xl border border-orange-200 hover:bg-orange-50 dark:hover:bg-[#1a1a20] flex items-center gap-2"><RefreshCw size={16} className={loading?'animate-spin':''}/> Refresh</button><button onClick={()=>setShowPrefs(!showPrefs)} className="px-4 py-2 rounded-lg border border-orange-200 hover:bg-orange-50 dark:hover:bg-[#1a1a20] flex items-center gap-2"><Settings2 size={16}/> Preferences</button><button onClick={markAll} className="px-4 py-2 rounded-lg bg-orange-500 hover:bg-orange-600 text-white flex items-center gap-2"><CheckCheck size={16}/> Mark all read</button></div></div>
  {showPrefs && prefs && <div className="mb-6 rounded-2xl border border-orange-100 bg-white dark:bg-[#111116] dark:border-gray-800 p-5"><h2 className="font-semibold mb-4">Notification preferences</h2><div className="grid md:grid-cols-2 gap-3">{[
   ['inAppEnabled','In-app notifications',Bell],['emailEnabled','Email notifications',Mail],['smsEnabled','SMS notifications',Smartphone],['whatsappEnabled','WhatsApp notifications',MessageSquare],['orderUpdates','Order updates',Bell],['lowStock','Low-stock alerts',Bell],['purchaseUpdates','Purchase updates',Bell],['loyaltyUpdates','Loyalty updates',Bell]
  ].map(([k,label,Icon]:any)=><label key={k} className="flex items-center justify-between rounded-xl border border-gray-100 dark:border-gray-800 p-3"><span className="flex items-center gap-2"><Icon size={16} className="text-orange-500"/>{label}</span><input type="checkbox" checked={!!prefs[k]} onChange={e=>setPrefs({...prefs,[k]:e.target.checked})}/></label>)}</div><div className="mt-4 flex justify-end"><button onClick={save} className="px-4 py-2 rounded-lg bg-orange-500 text-white">Save preferences</button></div><p className="text-xs text-gray-500 mt-3">Email, SMS and WhatsApp delivery are provider-ready and recorded as simulated until live provider credentials are configured.</p></div>}
  <div className="rounded-2xl border border-orange-100 bg-white dark:bg-[#111116] dark:border-gray-800 overflow-hidden">{loading?<div className="p-8 text-gray-500">Loading notifications…</div>:items.length===0?<div className="p-10 text-center text-gray-500">You’re all caught up. New operational events will appear here.</div>:<div>{items.map(n=><button key={n.id} onClick={async()=>{if(!n.readAt){await notificationApi.markRead(n.id);setItems(items.map(x=>x.id===n.id?{...x,readAt:new Date().toISOString()}:x))}}} className={`w-full text-left p-5 border-b border-gray-100 dark:border-gray-800 hover:bg-orange-50/50 dark:hover:bg-[#1a1a20] ${!n.readAt?'bg-orange-50/40 dark:bg-orange-950/10':''}`}><div className="flex gap-3"><div className="mt-1 w-2 h-2 rounded-full bg-orange-500 flex-shrink-0 opacity-80"></div><div className="flex-1"><div className="flex justify-between gap-4"><h3 className="font-semibold">{n.title}</h3><span className="text-xs text-gray-500 whitespace-nowrap">{new Date(n.createdAt).toLocaleString()}</span></div><p className="text-sm text-gray-600 dark:text-gray-300 mt-1">{n.message}</p><span className="text-xs text-orange-600 mt-2 inline-block">{n.type.replace(/_/g,' ')}</span></div></div></button>)}</div>}</div>
 </div>
}
