import { useEffect, useState } from 'react';
import { Clock3, LogIn, LogOut, RefreshCw } from 'lucide-react';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import Badge from '../../components/ui/Badge';
import Modal from '../../components/ui/Modal';
import Input from '../../components/ui/Input';
import { shiftApi } from '../../services/api';

const money=(n:number)=>`KES ${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export default function Shifts(){
 const [shifts,setShifts]=useState<any[]>([]),[current,setCurrent]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[open,setOpen]=useState(false),[close,setClose]=useState<any>(null);
 const [openingCash,setOpeningCash]=useState('0'),[notes,setNotes]=useState(''),[closingCash,setClosingCash]=useState(''),[filter,setFilter]=useState('');
 const load=async()=>{try{setLoading(true);setError('');const [a,b]=await Promise.all([shiftApi.getShifts(filter?{status:filter}:undefined),shiftApi.getCurrent()]);setShifts(a.data.data?.shifts||[]);setCurrent(b.data.data?.shift||null)}catch(e:any){setError(e.response?.data?.message||'Failed to load shifts')}finally{setLoading(false)}};
 useEffect(()=>{load()},[filter]);
 const start=async(e:any)=>{e.preventDefault();try{await shiftApi.open({openingCash:Number(openingCash),notes});setOpen(false);setOpeningCash('0');setNotes('');await load()}catch(e:any){setError(e.response?.data?.message||'Could not open shift')}};
 const finish=async(e:any)=>{e.preventDefault();try{await shiftApi.close(close.id,{closingCash:Number(closingCash)});setClose(null);setClosingCash('');await load()}catch(e:any){setError(e.response?.data?.message||'Could not close shift')}};
 return <div className="p-6 space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">Shifts</h1><p className="text-sm text-gray-500 dark:text-gray-400 mt-1">Open, monitor and close staff cash shifts.</p></div><div className="flex gap-2"><Button variant="secondary" onClick={load}><RefreshCw className="w-4 h-4 mr-2"/>Refresh</Button>{!current&&<Button onClick={()=>setOpen(true)}><LogIn className="w-4 h-4 mr-2"/>Open Shift</Button>}</div></div>{error&&<div className="rounded-lg border border-red-200 dark:border-red-800 bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-400 px-4 py-3 text-sm">{error}</div>}
 {current&&<Card className="border-orange-200 dark:border-orange-800"><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4"><div><div className="flex items-center gap-2"><Clock3 className="w-5 h-5 text-orange-600"/><h2 className="font-semibold text-gray-900 dark:text-gray-100">Your current shift</h2><Badge variant="success">OPEN</Badge></div><p className="text-sm text-gray-500 mt-2">Opened {new Date(current.openedAt).toLocaleString()}</p></div><div className="grid grid-cols-2 gap-5"><div><p className="text-xs text-gray-500 uppercase">Opening cash</p><p className="font-semibold">{money(current.openingCash)}</p></div><div><p className="text-xs text-gray-500 uppercase">Branch</p><p className="font-semibold">{current.branch?.name||'—'}</p></div></div><Button variant="danger" onClick={()=>{setClose(current);setClosingCash('')}}><LogOut className="w-4 h-4 mr-2"/>Close Shift</Button></div></Card>}
 <Card title="Shift history" actions={<select value={filter} onChange={e=>setFilter(e.target.value)} className="h-9 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-[#111116] px-3 text-sm"><option value="">All shifts</option><option value="OPEN">Open</option><option value="CLOSED">Closed</option></select>}>{loading?<div className="py-10 text-center text-gray-500">Loading shifts...</div>:<div className="overflow-x-auto"><table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700"><thead><tr>{['Staff','Branch','Opened','Closed','Opening','Expected','Closing','Variance','Status','Action'].map(h=><th key={h} className="px-4 py-3 text-left text-xs font-semibold uppercase text-gray-500">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-200 dark:divide-gray-700">{shifts.map(s=><tr key={s.id}><td className="px-4 py-3 text-sm font-medium">{s.userName}</td><td className="px-4 py-3 text-sm">{s.branchName}</td><td className="px-4 py-3 text-xs text-gray-500">{new Date(s.openedAt).toLocaleString()}</td><td className="px-4 py-3 text-xs text-gray-500">{s.closedAt?new Date(s.closedAt).toLocaleString():'—'}</td><td className="px-4 py-3 text-sm">{money(s.openingCash)}</td><td className="px-4 py-3 text-sm">{money(s.expectedCash)}</td><td className="px-4 py-3 text-sm">{s.closingCash!=null?money(s.closingCash):'—'}</td><td className="px-4 py-3 text-sm">{s.cashVariance!=null?<span className={s.cashVariance<0?'text-red-600':'text-green-600'}>{money(s.cashVariance)}</span>:'—'}</td><td className="px-4 py-3"><Badge variant={s.status==='OPEN'?'success':'default'}>{s.status}</Badge></td><td className="px-4 py-3">{s.status==='OPEN'&&s.userId===current?.userId&&<Button size="sm" variant="danger" onClick={()=>setClose(s)}>Close</Button>}</td></tr>)}{!shifts.length&&<tr><td colSpan={10} className="py-10 text-center text-sm text-gray-500">No shifts found.</td></tr>}</tbody></table></div>}</Card>
 {open&&<Modal title="Open Shift" onClose={()=>setOpen(false)}><form onSubmit={start} className="space-y-4"><Input id="openingCash" type="number" min="0" step="0.01" label="Opening Cash (KES)" value={openingCash} onChange={e=>setOpeningCash(e.target.value)} required/><label className="block text-sm font-medium text-gray-700 dark:text-gray-300">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} className="mt-1 w-full min-h-24 rounded-lg border border-gray-300 dark:border-gray-600 bg-white dark:bg-[#111116] px-3 py-2"/></label><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={()=>setOpen(false)}>Cancel</Button><Button type="submit">Open Shift</Button></div></form></Modal>}
 {close&&<Modal title="Close Shift" onClose={()=>setClose(null)}><form onSubmit={finish} className="space-y-4"><div className="rounded-lg bg-gray-50 dark:bg-[#111116]/70 p-4"><p className="text-sm text-gray-500">Shift opened</p><p className="font-semibold">{new Date(close.openedAt).toLocaleString()}</p><p className="text-sm text-gray-500 mt-3">Expected cash</p><p className="text-xl font-bold">{money(close.expectedCash)}</p></div><Input id="closingCash" type="number" min="0" step="0.01" label="Actual Closing Cash (KES)" value={closingCash} onChange={e=>setClosingCash(e.target.value)} required/><p className="text-xs text-gray-500">The system records the difference between actual and expected cash as the shift variance.</p><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={()=>setClose(null)}>Cancel</Button><Button type="submit" variant="danger">Close Shift</Button></div></form></Modal>}</div>
}
