import React, { useEffect, useMemo, useState } from 'react';
import { Download, Printer, RefreshCw, TrendingUp, ShoppingBag, CreditCard, BarChart3 } from 'lucide-react';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import Badge from '../../components/ui/Badge';
import { branchApi, reportApi } from '../../services/api';

const money = (n: number) => `KES ${Number(n || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const today = new Date().toISOString().slice(0, 10);
const thirtyDaysAgo = new Date(Date.now() - 29 * 86400000).toISOString().slice(0, 10);

export default function Reports() {
  const [startDate, setStartDate] = useState(thirtyDaysAgo), [endDate, setEndDate] = useState(today), [branchId, setBranchId] = useState('');
  const [branches, setBranches] = useState<any[]>([]), [data, setData] = useState<any>(null), [loading, setLoading] = useState(true), [error, setError] = useState('');
  const params = useMemo(() => ({ startDate, endDate, ...(branchId ? { branchId } : {}) }), [startDate, endDate, branchId]);
  const load = async () => { try { setLoading(true); setError(''); const r = await reportApi.getSalesReport(params); setData(r.data.data); } catch(e:any) { setError(e.response?.data?.message || 'Failed to load reports'); } finally { setLoading(false); } };
  useEffect(() => {
    branchApi.getBranches().then(r => {
      const payload = r.data?.data;
      const list = Array.isArray(payload) ? payload : payload?.branches;
      setBranches(Array.isArray(list) ? list : []);
    }).catch(() => setBranches([]));
  }, []);
  useEffect(() => { load(); }, [params]);
  const exportReport = async (type:string) => { try { const r=await reportApi.exportSalesReport({...params,type}); const blob=new Blob([r.data],{type:'text/csv;charset=utf-8'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=`sales-report-${type}-${endDate}.csv`; a.click(); URL.revokeObjectURL(url); } catch(e:any){setError(e.response?.data?.message||'Export failed')} };
  const s=data?.summary||{}, maxProduct=Math.max(...(data?.byProduct||[]).slice(0,8).map((x:any)=>x.sales),1);
  return <div className="p-6 space-y-6 print:p-0">
    <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4 print:hidden"><div><h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">Sales & Management Reports</h1><p className="text-sm text-gray-500 dark:text-gray-400 mt-1">Analyze sales, products, customers, cashiers, branches and payments.</p></div><div className="flex gap-2"><Button variant="secondary" onClick={load} className="gap-2"><RefreshCw className="w-4 h-4"/>Refresh</Button><Button variant="secondary" onClick={()=>window.print()} className="gap-2"><Printer className="w-4 h-4"/>Print</Button></div></div>
    <Card className="print:hidden"><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><label className="text-sm">From<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} className="mt-1 h-10 w-full rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-[#111116] px-3"/></label><label className="text-sm">To<input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)} className="mt-1 h-10 w-full rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-[#111116] px-3"/></label><label className="text-sm">Branch<select value={branchId} onChange={e=>setBranchId(e.target.value)} className="mt-1 h-10 w-full rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-[#111116] px-3"><option value="">All branches</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div></Card>
    {error&&<div className="bg-red-50 dark:bg-red-900/30 border border-red-200 dark:border-red-800 text-red-700 dark:text-red-400 px-4 py-3 rounded-md">{error}</div>}
    {loading ? <div className="py-16 text-center text-gray-500">Loading report...</div> : error || !data ? <div className="rounded-lg border border-red-200 bg-red-50 dark:bg-red-900/20 dark:border-red-800 p-6 text-red-700 dark:text-red-300"><h2 className="font-semibold">Unable to load reports</h2><p className="mt-1 text-sm">{error || 'No report data was returned by the server.'}</p><Button variant="secondary" onClick={load} className="mt-4">Try again</Button></div> : <>
      <div className="hidden print:block mb-5"><h1 className="text-2xl font-bold">Sales Report</h1><p>{startDate} to {endDate}{branchId?` • ${branches.find(b=>b.id===branchId)?.name||''}`:''}</p></div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4"><Metric title="Sales" value={money(s.grossSales)} icon={TrendingUp}/><Metric title="Orders" value={s.orderCount||0} icon={ShoppingBag}/><Metric title="Average Order" value={money(s.averageOrderValue)} icon={BarChart3}/><Metric title="Estimated Profit" value={money(s.grossProfitEstimate)} icon={CreditCard}/></div>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><Card title="Sales Summary" description="Completed orders in selected period"><div className="space-y-3 text-sm">{[['Gross sales',s.grossSales],['Discounts',s.totalDiscounts],['Tax',s.totalTax],['Service charge',s.totalServiceCharge],['Estimated cost',s.totalCost],['Estimated profit',s.grossProfitEstimate]].map(([k,v]:any)=><div className="flex justify-between border-b border-gray-100 dark:border-gray-700 pb-2" key={k}><span className="text-gray-500 dark:text-gray-400">{k}</span><span className="font-medium">{money(v)}</span></div>)}</div></Card><Card title="Payment Methods" description="Completed payment transactions"><ReportTable rows={data.byPaymentMethod} headers={['Method','Transactions','Amount']} render={(r:any)=><><td>{String(r.method).replace('_',' ')}</td><td>{r.transactions}</td><td>{money(r.amount)}</td></>}/></Card><Card title="Top Customers" description="Highest spending customers"><ReportTable rows={(data.customerSpending||[]).slice(0,6)} headers={['Customer','Orders','Spent']} render={(r:any)=><><td>{r.name}</td><td>{r.orders}</td><td>{money(r.spent)}</td></>}/></Card></div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><Card title="Discount Performance" description="Discounts granted by promotion"><ReportTable rows={data.byPromotion} headers={['Promotion','Orders','Discounts']} render={(r:any)=><><td>{r.name}</td><td>{r.orders}</td><td>{money(r.discounts)}</td></>}/></Card><Card title="Best-Selling Products" description="Ranked by sales value"><div className="space-y-4">{(data.byProduct||[]).slice(0,8).map((r:any)=><div key={r.id}><div className="flex justify-between text-sm mb-1"><span>{r.name}</span><span className="font-medium">{money(r.sales)}</span></div><div className="h-2 rounded bg-gray-100 dark:bg-[#111116]"><div className="h-2 rounded bg-orange-600" style={{width:`${Math.max(4,r.sales/maxProduct*100)}%`}}/></div><p className="text-xs text-gray-500 mt-1">{r.quantity} sold • Est. profit {money(r.sales-r.cost)}</p></div>)}{!data.byProduct?.length&&<p className="text-sm text-gray-500">No completed sales in this period.</p>}</div></Card><Card title="Sales by Category" description="Category performance"><ReportTable rows={data.byCategory} headers={['Category','Qty','Sales']} render={(r:any)=><><td>{r.name}</td><td>{r.quantity}</td><td>{money(r.sales)}</td></>}/></Card></div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6"><Card title="Sales by Cashier" description="Completed orders by staff member"><ReportTable rows={data.byCashier} headers={['Cashier','Orders','Sales']} render={(r:any)=><><td>{r.name}</td><td>{r.orders}</td><td>{money(r.sales)}</td></>}/></Card><Card title="Sales by Branch" description="Branch comparison"><ReportTable rows={data.byBranch} headers={['Branch','Orders','Sales']} render={(r:any)=><><td>{r.name}</td><td>{r.orders}</td><td>{money(r.sales)}</td></>}/></Card></div>
      <Card title="Completed Orders" description={`${data.orders?.length||0} orders in the selected period`}><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b dark:border-gray-700 text-left text-xs uppercase text-gray-500">{['Order','Date','Branch','Cashier','Customer','Total','Payment'].map(h=><th key={h} className="py-3 pr-4">{h}</th>)}</tr></thead><tbody className="divide-y dark:divide-gray-700">{(data.orders||[]).slice(0,100).map((r:any)=><tr key={r.id}><td className="py-3 pr-4 font-medium">{r.orderNumber}</td><td className="py-3 pr-4 text-gray-500">{new Date(r.date).toLocaleString()}</td><td className="py-3 pr-4">{r.branch}</td><td className="py-3 pr-4">{r.cashier}</td><td className="py-3 pr-4">{r.customer}</td><td className="py-3 pr-4">{money(r.total)}</td><td className="py-3"><Badge variant={r.paymentStatus==='PAID'?'success':'warning'}>{r.paymentStatus}</Badge></td></tr>)}</tbody></table></div></Card>
      <div className="flex flex-wrap gap-2 print:hidden"><span className="text-sm text-gray-500 self-center mr-2">Export:</span>{['orders','products','categories','cashiers','branches','payments','customers'].map(type=><Button key={type} variant="secondary" onClick={()=>exportReport(type)} className="gap-2"><Download className="w-4 h-4"/>{type}</Button>)}</div>
    </>}
  </div>;
}
function Metric({title,value,icon:Icon}:{title:string;value:any;icon:any}){return <Card><div className="flex justify-between"><div><p className="text-sm text-gray-500 dark:text-gray-400">{title}</p><p className="text-xl font-bold mt-1">{value}</p></div><Icon className="w-6 h-6 text-gray-400"/></div></Card>}
function ReportTable({rows,headers,render}:{rows:any[];headers:string[];render:(r:any)=>React.ReactNode}){return <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b dark:border-gray-700 text-xs uppercase text-gray-500">{headers.map(h=><th key={h} className="py-2 pr-3 text-left">{h}</th>)}</tr></thead><tbody className="divide-y dark:divide-gray-700">{(rows||[]).slice(0,10).map((r:any,i)=><tr key={r.id||r.method||i} className="align-top">{render(r)}</tr>)}{!rows?.length&&<tr><td colSpan={headers.length} className="py-5 text-gray-500">No data.</td></tr>}</tbody></table></div>}
