import { useEffect, useState } from 'react';
import { Search, RotateCcw, Printer } from 'lucide-react';
import Card from '../../components/ui/Card';
import Badge from '../../components/ui/Badge';
import Modal from '../../components/ui/Modal';
import { paymentApi, orderApi } from '../../services/api';

export default function Payments() {
  const [payments, setPayments] = useState<any[]>([]);
  const [search, setSearch] = useState('');
  const [method, setMethod] = useState('');
  const [status, setStatus] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [orderId, setOrderId] = useState('');
  const [orders, setOrders] = useState<any[]>([]);
  const [selectedOrder, setSelectedOrder] = useState<any>(null);
  const [payMethod, setPayMethod] = useState('CASH');
  const [amount, setAmount] = useState('');
  const [tendered, setTendered] = useState('');

  const load = async () => { try { setLoading(true); const r = await paymentApi.getPayments({ search, method, status }); setPayments(r.data.data || []); } catch(e:any){setError(e.response?.data?.message||'Failed to load payments')} finally{setLoading(false)} };
  useEffect(()=>{load()},[search,method,status]);
  useEffect(()=>{ orderApi.getOrders({limit:'100', status:'COMPLETED'}).then(r=>setOrders((r.data.data?.orders||[]).filter((o:any)=>o.paymentStatus!=='PAID'))).catch(()=>{}) },[]);
  const openPay=(o:any)=>{setSelectedOrder(o);const due=Math.max(0,o.totalAmount-(o.amountPaid||0));setAmount(due.toFixed(2));setTendered(due.toFixed(2));setPayMethod('CASH')};
  const pay=async()=>{try{await paymentApi.recordPayment(selectedOrder.id,{method:payMethod,amount:Number(amount),amountTendered:payMethod==='CASH'?Number(tendered):Number(amount)});setSelectedOrder(null);load();const r=await orderApi.getOrders({limit:'100',status:'COMPLETED'});setOrders((r.data.data?.orders||[]).filter((o:any)=>o.paymentStatus!=='PAID'))}catch(e:any){setError(e.response?.data?.message||'Payment failed')}};
  const refund=async(p:any)=>{const reason=prompt('Refund reason:');if(!reason)return;try{await paymentApi.refundPayment(p.id,{reason});load()}catch(e:any){setError(e.response?.data?.message||'Refund failed')}};
  const receipt=async(p:any)=>{try{const r=await paymentApi.getReceipt(p.sale.id);const d=r.data.data;const w=window.open('','_blank','width=420,height=700');if(!w)return;const rows=d.sale.items.map((i:any)=>`<tr><td>${i.quantity}x ${i.itemNameSnapshot}</td><td style="text-align:right">KES ${Number(i.subtotal || 0).toLocaleString()}</td></tr>`).join('');w.document.write(`<html><body style="font-family:Arial;padding:24px"><h2 style="text-align:center">${d.sale.branch.name}</h2><p style="text-align:center">Receipt ${d.receipt.receiptNumber}<br>Order ${d.sale.orderNumber}</p><table style="width:100%">${rows}</table><h3>Total: KES ${Number(d.sale.totalAmount || 0).toLocaleString()}</h3><script>window.print()</script></body></html>`);w.document.close()}catch(e:any){setError(e.response?.data?.message||'Receipt failed')}};
  return <div className="p-6 space-y-6"><div><h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100">Payments</h1><p className="text-sm text-gray-500 dark:text-gray-400 mt-1">Record payments, manage split payments and receipts.</p></div>{error&&<div className="bg-red-50 dark:bg-red-900/30 border border-red-200 dark:border-red-800 text-red-700 dark:text-red-400 px-4 py-3 rounded-md text-sm">{error}</div>}
  <Card><div className="grid grid-cols-1 md:grid-cols-4 gap-3 mb-5"><div className="relative"><Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 pointer-events-none"/><input placeholder="Search order/reference" value={search} onChange={e=>setSearch(e.target.value)} className="h-10 w-full pl-10 pr-4 rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-[#111116] text-sm"/></div><select value={method} onChange={e=>setMethod(e.target.value)} className="h-10 rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-[#111116] px-3 text-sm"><option value="">All methods</option><option value="CASH">Cash</option><option value="CARD">Card</option><option value="MOBILE_MONEY">Mobile Money</option></select><select value={status} onChange={e=>setStatus(e.target.value)} className="h-10 rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-[#111116] px-3 text-sm"><option value="">All payment statuses</option><option value="COMPLETED">Completed</option><option value="REFUNDED">Refunded</option></select><select value={orderId} onChange={e=>{setOrderId(e.target.value);const o=orders.find(x=>x.id===e.target.value);if(o)openPay(o)}} className="h-10 rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-[#111116] px-3 text-sm"><option value="">Pay completed order...</option>{orders.map(o=><option key={o.id} value={o.id}>{o.orderNumber} — KES {Math.max(0,Number(o.totalAmount || 0)-(o.amountPaid||0)).toLocaleString()}</option>)}</select></div>
  {loading?<div className="py-10 text-center text-gray-500">Loading payments...</div>:<div className="overflow-x-auto"><table className="min-w-full divide-y divide-gray-200 dark:divide-gray-700"><thead className="bg-[#faf9f7] dark:bg-[#111116]/70"><tr>{['Payment','Order','Method','Amount','Status','Date','Actions'].map(h=><th key={h} className="px-5 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase">{h}</th>)}</tr></thead><tbody className="divide-y divide-gray-200 dark:divide-gray-700">{payments.map(p=><tr key={p.id}><td className="px-5 py-4 text-sm font-medium">{p.reference||p.id.slice(0,8)}</td><td className="px-5 py-4 text-sm">{p.sale?.orderNumber || '—'}</td><td className="px-5 py-4 text-sm">{(p.method || '').replace('_',' ')}</td><td className="px-5 py-4 text-sm font-medium">KES {Number(p.amount || 0).toLocaleString()}</td><td className="px-5 py-4"><Badge variant={p.status==='COMPLETED'?'success':'danger'}>{p.status}</Badge></td><td className="px-5 py-4 text-xs text-gray-500">{p.createdAt ? new Date(p.createdAt).toLocaleString() : '—'}</td><td className="px-5 py-4"><button onClick={()=>receipt(p)} className="mr-3 text-orange-600" title="Receipt"><Printer className="w-4 h-4"/></button>{p.status==='COMPLETED'&&<button onClick={()=>refund(p)} className="text-red-600" title="Refund"><RotateCcw className="w-4 h-4"/></button>}</td></tr>)}{payments.length===0&&<tr><td colSpan={7} className="py-10 text-center text-sm text-gray-500">No payments found.</td></tr>}</tbody></table></div>}</Card>
  {selectedOrder&&<Modal title={`Record Payment — ${selectedOrder.orderNumber}`} onClose={()=>setSelectedOrder(null)}><div className="space-y-4"><div className="grid grid-cols-2 gap-4"><div><p className="text-xs text-gray-500">TOTAL</p><p className="font-semibold">KES {Number(selectedOrder.totalAmount || 0).toLocaleString()}</p></div><div><p className="text-xs text-gray-500">DUE</p><p className="font-semibold">KES {Math.max(0,Number(selectedOrder.totalAmount || 0)-(selectedOrder.amountPaid||0)).toLocaleString()}</p></div></div><label className="block text-sm">Method<select value={payMethod} onChange={e=>setPayMethod(e.target.value)} className="mt-1 w-full h-10 rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-[#111116] px-3"><option value="CASH">Cash</option><option value="CARD">Card</option><option value="MOBILE_MONEY">Mobile Money</option></select></label><label className="block text-sm">Amount<input type="number" value={amount} onChange={e=>setAmount(e.target.value)} className="mt-1 w-full h-10 rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-[#111116] px-3"/></label>{payMethod==='CASH'&&<label className="block text-sm">Amount tendered<input type="number" value={tendered} onChange={e=>setTendered(e.target.value)} className="mt-1 w-full h-10 rounded-md border border-gray-300 dark:border-gray-600 bg-white dark:bg-[#111116] px-3"/></label>}<button onClick={pay} className="w-full h-10 bg-orange-600 text-white rounded-md font-medium">Record Payment</button></div></Modal>}</div>;
}
